export const authTypes = {
  LOGIN_USER: "LOGIN_USER",
  LOGIN_ERROR: "LOGIN_ERROR",
  CLEAR_ERROR: "CLEAR_ERROR",
  LOGOUT_USER: "LOGOUT_USER",
};

export const authRegisterTypes = {
  REGISTER_USER: "REGISTER_USER",
  REGISTER_ERROR: "REGISTER_ERROR",
  CLEAR_REGISTER_ERROR: "CLEAR_REGISTER_ERROR",
};
